# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_resetJobStats
    rt::HARTNDb_resetSystemStats
    rt::HARTNDb_startSystemStats
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "C:/DSD_Streamline_try/.Xil/Vivado-9476-minjin-laptop/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file delete -force $::env(RT_TMP)
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    set rt::partid xc7z020clg400-1
     file delete -force synth_hints.os

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common_vhdl.tcl
    set rt::defaultWorkLibName xil_defaultlib

    set rt::useElabCache false
    if {$rt::useElabCache == false} {
      rt::read_verilog -sv -include {
    c:/DSD_Streamline_try/dsd_mlp.srcs/sources_1/bd/design_1/ipshared/1ddd/hdl/verilog
    c:/DSD_Streamline_try/dsd_mlp.srcs/sources_1/bd/design_1/ipshared/b2d0/hdl/verilog
  } {
      c:/DSD_Streamline_try/dsd_mlp.srcs/sources_1/bd/design_1/ipshared/1ddd/hdl/sc_util_v1_0_vl_rfs.sv
      c:/DSD_Streamline_try/dsd_mlp.srcs/sources_1/bd/design_1/ipshared/f85e/hdl/sc_mmu_v1_0_vl_rfs.sv
      c:/DSD_Streamline_try/dsd_mlp.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_2/synth/bd_48ac_s00mmu_0.sv
      c:/DSD_Streamline_try/dsd_mlp.srcs/sources_1/bd/design_1/ipshared/ca72/hdl/sc_transaction_regulator_v1_0_vl_rfs.sv
      c:/DSD_Streamline_try/dsd_mlp.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_3/synth/bd_48ac_s00tr_0.sv
      c:/DSD_Streamline_try/dsd_mlp.srcs/sources_1/bd/design_1/ipshared/7de4/hdl/sc_si_converter_v1_0_vl_rfs.sv
      c:/DSD_Streamline_try/dsd_mlp.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_4/synth/bd_48ac_s00sic_0.sv
      c:/DSD_Streamline_try/dsd_mlp.srcs/sources_1/bd/design_1/ipshared/b89e/hdl/sc_axi2sc_v1_0_vl_rfs.sv
      c:/DSD_Streamline_try/dsd_mlp.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_5/synth/bd_48ac_s00a2s_0.sv
      c:/DSD_Streamline_try/dsd_mlp.srcs/sources_1/bd/design_1/ipshared/b2d0/hdl/sc_node_v1_0_vl_rfs.sv
      c:/DSD_Streamline_try/dsd_mlp.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_6/synth/bd_48ac_sarn_0.sv
      c:/DSD_Streamline_try/dsd_mlp.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_7/synth/bd_48ac_srn_0.sv
      c:/DSD_Streamline_try/dsd_mlp.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_8/synth/bd_48ac_sawn_0.sv
      c:/DSD_Streamline_try/dsd_mlp.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_9/synth/bd_48ac_swn_0.sv
      c:/DSD_Streamline_try/dsd_mlp.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_10/synth/bd_48ac_sbn_0.sv
      c:/DSD_Streamline_try/dsd_mlp.srcs/sources_1/bd/design_1/ipshared/7005/hdl/sc_sc2axi_v1_0_vl_rfs.sv
      c:/DSD_Streamline_try/dsd_mlp.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_11/synth/bd_48ac_m00s2a_0.sv
      c:/DSD_Streamline_try/dsd_mlp.srcs/sources_1/bd/design_1/ipshared/b387/hdl/sc_exit_v1_0_vl_rfs.sv
      c:/DSD_Streamline_try/dsd_mlp.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_12/synth/bd_48ac_m00e_0.sv
      C:/Xilinx/Vivado/2019.1/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv
      C:/Xilinx/Vivado/2019.1/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv
      C:/Xilinx/Vivado/2019.1/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv
    }
      rt::read_verilog -include {
    c:/DSD_Streamline_try/dsd_mlp.srcs/sources_1/bd/design_1/ipshared/1ddd/hdl/verilog
    c:/DSD_Streamline_try/dsd_mlp.srcs/sources_1/bd/design_1/ipshared/b2d0/hdl/verilog
  } {
      C:/DSD_Streamline_try/dsd_mlp.srcs/sources_1/new/glbl_ctrl.v
      C:/DSD_Streamline_try/dsd_mlp.srcs/sources_1/new/layer1.v
      C:/DSD_Streamline_try/dsd_mlp.srcs/sources_1/new/layer2.v
      C:/DSD_Streamline_try/dsd_mlp.srcs/sources_1/new/layer3.v
      C:/DSD_Streamline_try/dsd_mlp.srcs/sources_1/new/layer4.v
      C:/DSD_Streamline_try/dsd_mlp.srcs/sources_1/new/layer5.v
      C:/DSD_Streamline_try/dsd_mlp.srcs/sources_1/new/local_ctrl_layer1.v
      C:/DSD_Streamline_try/dsd_mlp.srcs/sources_1/new/local_ctrl_layer2.v
      C:/DSD_Streamline_try/dsd_mlp.srcs/sources_1/new/local_ctrl_layer3.v
      C:/DSD_Streamline_try/dsd_mlp.srcs/sources_1/new/local_ctrl_layer4.v
      C:/DSD_Streamline_try/dsd_mlp.srcs/sources_1/new/local_ctrl_layer5.v
      C:/DSD_Streamline_try/dsd_mlp.srcs/sources_1/new/mac.v
      C:/DSD_Streamline_try/dsd_mlp.srcs/sources_1/new/pu.v
      C:/DSD_Streamline_try/dsd_mlp.srcs/sources_1/new/pu_3.v
      C:/DSD_Streamline_try/dsd_mlp.srcs/sources_1/new/single_port_bram.v
      C:/DSD_Streamline_try/dsd_mlp.srcs/sources_1/new/temp_bram.v
      C:/DSD_Streamline_try/dsd_mlp.srcs/sources_1/new/temp_buf.v
      C:/DSD_Streamline_try/dsd_mlp.srcs/sources_1/new/top.v
      C:/DSD_Streamline_try/dsd_mlp.srcs/sources_1/new/top_mlp.v
      c:/DSD_Streamline_try/dsd_mlp.srcs/sources_1/bd/design_1/ipshared/8fd3/hdl/verilog/processing_system7_v5_5_aw_atc.v
      c:/DSD_Streamline_try/dsd_mlp.srcs/sources_1/bd/design_1/ipshared/8fd3/hdl/verilog/processing_system7_v5_5_b_atc.v
      c:/DSD_Streamline_try/dsd_mlp.srcs/sources_1/bd/design_1/ipshared/8fd3/hdl/verilog/processing_system7_v5_5_w_atc.v
      c:/DSD_Streamline_try/dsd_mlp.srcs/sources_1/bd/design_1/ipshared/8fd3/hdl/verilog/processing_system7_v5_5_atc.v
      c:/DSD_Streamline_try/dsd_mlp.srcs/sources_1/bd/design_1/ipshared/8fd3/hdl/verilog/processing_system7_v5_5_trace_buffer.v
      c:/DSD_Streamline_try/dsd_mlp.srcs/sources_1/bd/design_1/ip/design_1_processing_system7_0_0/hdl/verilog/processing_system7_v5_5_processing_system7.v
      c:/DSD_Streamline_try/dsd_mlp.srcs/sources_1/bd/design_1/ip/design_1_processing_system7_0_0/synth/design_1_processing_system7_0_0.v
      c:/DSD_Streamline_try/dsd_mlp.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/synth/design_1_smartconnect_0_0.v
      c:/DSD_Streamline_try/dsd_mlp.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/synth/bd_48ac.v
      c:/DSD_Streamline_try/dsd_mlp.srcs/sources_1/bd/design_1/ipshared/66e7/hdl/xlconstant_v1_1_vl_rfs.v
      c:/DSD_Streamline_try/dsd_mlp.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_0/synth/bd_48ac_one_0.v
      c:/DSD_Streamline_try/dsd_mlp.srcs/sources_1/bd/design_1/ip/design_1_top_mlp_0_0/synth/design_1_top_mlp_0_0.v
      C:/DSD_Streamline_try/dsd_mlp.srcs/sources_1/bd/design_1/synth/design_1.v
      C:/DSD_Streamline_try/dsd_mlp.srcs/sources_1/bd/design_1/hdl/design_1_wrapper.v
    }
      rt::read_vhdl -lib lib_cdc_v1_0_2 c:/DSD_Streamline_try/dsd_mlp.srcs/sources_1/bd/design_1/ipshared/ef1e/hdl/lib_cdc_v1_0_rfs.vhd
      rt::read_vhdl -lib proc_sys_reset_v5_0_13 c:/DSD_Streamline_try/dsd_mlp.srcs/sources_1/bd/design_1/ipshared/8842/hdl/proc_sys_reset_v5_0_vh_rfs.vhd
      rt::read_vhdl -lib xil_defaultlib {
      c:/DSD_Streamline_try/dsd_mlp.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_1/synth/bd_48ac_psr_aclk_0.vhd
      c:/DSD_Streamline_try/dsd_mlp.srcs/sources_1/bd/design_1/ip/design_1_axi_bram_ctrl_0_0/synth/design_1_axi_bram_ctrl_0_0.vhd
      c:/DSD_Streamline_try/dsd_mlp.srcs/sources_1/bd/design_1/ip/design_1_axi_bram_ctrl_0_bram_2/synth/design_1_axi_bram_ctrl_0_bram_2.vhd
    }
      rt::read_vhdl -lib axi_bram_ctrl_v4_1_1 c:/DSD_Streamline_try/dsd_mlp.srcs/sources_1/bd/design_1/ipshared/70bf/hdl/axi_bram_ctrl_v4_1_rfs.vhd
      rt::read_vhdl -lib blk_mem_gen_v8_4_3 c:/DSD_Streamline_try/dsd_mlp.srcs/sources_1/bd/design_1/ipshared/c001/hdl/blk_mem_gen_v8_4_vhsyn_rfs.vhd
      rt::read_vhdl -lib xpm C:/Xilinx/Vivado/2019.1/data/ip/xpm/xpm_VCOMP.vhd
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification false
    set rt::top design_1_wrapper
    rt::set_parameter enableIncremental true
    set rt::reportTiming false
    rt::set_parameter elaborateOnly true
    rt::set_parameter elaborateRtl true
    rt::set_parameter eliminateRedundantBitOperator false
    rt::set_parameter elaborateRtlOnlyFlow true
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter merge_flipflops true
    rt::set_parameter srlDepthThreshold 3
    rt::set_parameter rstSrlDepthThreshold 4
# MODE: 
    rt::set_parameter webTalkPath {}
    rt::set_parameter enableSplitFlowPath "C:/DSD_Streamline_try/.Xil/Vivado-9476-minjin-laptop/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
        $rt::db readXRFFile
      rt::run_rtlelab -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    if { $rt::flowresult == 1 } { return -code error }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
